### ISSUE TITLE
Remove the stacktrace from the log 

### ISSUE THREAD

**Issue by varadha2k** [reportportal/agent-java-jbehave#12]
I am using JBehave agent version 4.0.1.  I am using the following code to assert

assertTrue("The following is the list of failures" + errorMessage, success);

So when there is a failure, I would like to see a custom message shown in the log in reportportal.

But when there is a failure, along with the custom message, stack trace is also thrown. I am able to trace the reason for it and it in below give method in com.epam.reportportal.jbehave.JBehaveUtils

	public static void sendStackTraceToRP(final Throwable cause) {

		ReportPortal.emitLog(new Function<String, SaveLogRQ>() {
			@Override
			public SaveLogRQ apply(String itemId) {
				SaveLogRQ rq = new SaveLogRQ();
				rq.setTestItemId(itemId);
				rq.setLevel("ERROR");
				rq.setLogTime(Calendar.getInstance().getTime());
				if (cause != null) {
					rq.setMessage(getStackTraceAsString(cause));
				} else {
					rq.setMessage("Test has failed without exception");
				}
				rq.setLogTime(Calendar.getInstance().getTime());

				return rq;
			}
		});
	}

Here "getStackTraceAsString", add stack trace along with the custom message. How do I remove the stack trace from this log for better readability. 

org.jbehave.core.failures.UUIDExceptionWrapper: Then Compare the Expected values with Actual values for given xpath: 
|xpath|expectedvalue| 
|/path/text()|Expected Value| 
at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:752) 
at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:346) 
at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1090) 
at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:955) 
at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:994) 
at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:904) 
at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:825) 
at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:798) 
at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:422) 
at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:393) 
at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:292) 
at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266) 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
at java.lang.Thread.run(Thread.java:745) 
Caused by: java.lang.NullPointerException 
at com.automation.steps.ExtractWorkFlow.throwMangledException(ExtractWorkFlow.java:284) 
at com.automation.steps.ExtractWorkFlow.elementsXpathsCompare(ExtractWorkFlow.java:269) 
at com.automation.steps.ExtractWorkFlow$$FastClassBySpringCGLIB$$a5d0ab65.invoke(<generated>) 
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) 
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) 
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) 
at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62) 
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) 
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) 
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) 
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673) 
at com.automation.steps.ExtractWorkFlow$$EnhancerBySpringCGLIB$$fc879127.elementsXpathsCompare(<generated>) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:498) 
at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:733) 
... 15 more

**Comment by HardNorth** [comment]
The issue caused by outdated version of the agent, please use the latest one: https://github.com/reportportal/agent-java-jbehave/releases
Now you can override this method and mute stack traces: https://github.com/reportportal/agent-java-jbehave/blob/develop/src/main/java/com/epam/reportportal/jbehave/ReportPortalStoryReporter.java#L666

But be aware that you leave very little space for auto-analysis in this case. For it the more data it has the better.
