### ISSUE TITLE
ArrayIndexOutOfBoundEcxeption in retrieveLeaf() of ReportPortalStoryReporter class while running story files in Jbehave

### ISSUE THREAD

**Issue by snehalavhare** [reportportal/agent-java-jbehave#50]
HI, I am working on integration of report portal with my jbehave framework, where I am using ReportPortalScenarioFormat. INSTANCE or ReportPortalStepFormat.INSTANCE 
but after running the first scenario successfully , 2nd scenario is getting failed with ArrayIndexOutOfBoundEcxeption in retrieveLeaf() method of  ReportPortalStoryReporter class.

Can somebody please help with the cause of this error?

I am using Agent version : agent-java-jbehave 5.0.0 -RC - 2 and Rp version 5.3.5.

I have used guide https://github.com/reportportal/agent-java-jbehave for integration.

**Below is the story file structure:**
perform card setup of photo credit card device
Narrative:
In order to verify card setup of photo credit card device
As a user 
I want to perform card setup of photo credit msr card device

Meta:
@StoryName credit_msr_retail_photo
	 
Scenario: 1.1 To verify Photo Reference number is present in embossing file
Given setting json values in excel for Credit
When user gets card plans from excel for CREDIT_NEW_DEVICE_PHOTO_CARD scenario to onboard Credit product
When user gets card plans from excel for CREDIT_NEW_DEVICE_PHOTO_CARD scenario to onboard Credit product
Then user gets card plans from excel for CREDIT_NEW_DEVICE_PHOTO_CARD scenario to onboard Credit product

Scenario: 1.2 To verify Photo Reference number is present in embossing file
Given user is logged in institution
When user gets card plans from excel for CREDIT_NEW_DEVICE_PHOTO_CARD scenario to onboard Credit product
Then user sign out from customer portal

**Comment by snehalavhare** [comment]
Please see below the stack trace:

- TEST PASSED -
---------------
TEST PASSED: 1 Verify that request is successful when Block API request is triggered for device with correct parameters and device gets blocked- CRD
---------------- 
2021-03-08 01:29:24,098 INFO  [CustomStoryReporter] <=== Scenario finished. Verdict is  PASSED  
2021-03-08 01:29:24,159 INFO  [Serenity] 
----------------
- TEST STARTED -
----------------
TEST STARTED: 2 Verify that request is unsuccessful if request to unblock device request to block device is with invalid channel id
----------------- 
2021-03-08 01:29:24,159 INFO  [CustomStoryReporter] ===> Executing scenario: 2 Verify that request is unsuccessful if request to unblock device request to block device is with invalid channel id 
2021-03-08 01:29:24,159 INFO  [CustomStoryReporter] ===> Test ID:  
2021-03-08 01:29:24,161 INFO  [TestHooks] TestCase ID Before Scenario: block_device_invalid_channel_id 
2021-03-08 01:29:24,187 INFO  [Serenity] STARTING STEP Given user creates json request 
[WARNING] Failed to run story stories/API/Rest/deviceapi/cardholder/card_block_unblock_R.story
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at com.epam.reportportal.jbehave.ReportPortalStoryReporter.retrieveLeaf(ReportPortalStoryReporter.java:499)
	at com.epam.reportportal.jbehave.ReportPortalStoryReporter.beforeStep(ReportPortalStoryReporter.java:808)
	at org.jbehave.core.reporters.DelegatingStoryReporter.beforeStep(DelegatingStoryReporter.java:142)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.beforeStep(ConcurrentStoryReporter.java:247)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.describeTo(StepCreator.java:724)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:344)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1088)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:953)
	at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:992)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:902)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:825)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:798)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:422)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:393)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:292)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Generating reports view to 'D:\Jenkins\workspace\TestJobs\SnehaL\New_Scenarios_Execution\target\jbehave' using formats '[stats, serenityreporter, ide_console, stats, html, xml, report_portal, customstoryreporter]' and view properties '{decorateNonHtml=true}'
[INFO]

**Comment by snehalavhare** [comment]
Please see below the stack traces:


---------------
- TEST PASSED -
---------------
TEST PASSED: 1.1 To verify Photo Reference number is present in embossing file
---------------- 
2021-03-07 23:28:55,071 INFO  [CustomStoryReporter] <=== Scenario finished. Verdict is  PASSED  
2021-03-07 23:28:55,082 INFO  [Serenity] 
----------------
- TEST STARTED -
----------------
TEST STARTED: 1.2 To verify Photo Reference number is present in embossing file
----------------- 
2021-03-07 23:28:55,094 INFO  [CustomStoryReporter] ===> Executing scenario: 1.2 To verify Photo Reference number is present in embossing file, cGiven setting json values in excel for Credit 
2021-03-07 23:28:55,094 INFO  [CustomStoryReporter] ===> Test ID:  
2021-03-07 23:28:55,095 INFO  [TestHooks] TestCase ID Before Scenario:  
2021-03-07 23:28:55,106 INFO  [Serenity] STARTING STEP Given user is logged in institution 
[WARNING] Failed to run story stories/UI/Regression/Application_Boarding/MasterCard/Account_And_Card_Setup/Credit/testReportPortal.story
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at com.epam.reportportal.jbehave.ReportPortalStoryReporter.retrieveLeaf(ReportPortalStoryReporter.java:499)
	at com.epam.reportportal.jbehave.ReportPortalStoryReporter.beforeStep(ReportPortalStoryReporter.java:808)
	at org.jbehave.core.reporters.DelegatingStoryReporter.beforeStep(DelegatingStoryReporter.java:142)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.beforeStep(ConcurrentStoryReporter.java:247)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.describeTo(StepCreator.java:724)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:344)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1088)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:953)
	at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:992)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:902)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:825)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:798)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:422)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:393)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:292)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Generating reports view to 'D:\Jenkins\workspace\TestJobs\SnehaL\New_Scenarios_Execution\target\jbehave' using formats '[stats, serenityreporter, ide_console, stats, html, xml, report_portal, customstoryreporter]' and view properties '{decorateNonHtml=true}'

**Comment by HardNorth** [comment]
@snehalavhare As per conversation in Slack you need to update your JBehave version. RP supports JBehave versions >= 4.8 only. Since it's literally impossible to implement a reporter for older versions due to bugs.

Moreover I implemented a test on your particular case and it passes: https://github.com/reportportal/agent-java-jbehave/blob/develop/src/test/java/com/epam/reportportal/jbehave/TwoScenarioTest.java
