### ISSUE TITLE
IAE when examples table parameter has $ character

### ISSUE THREAD

**Issue by ikalinin1** [reportportal/agent-java-jbehave#59]
```
java.lang.IllegalArgumentException: No group with name {videoTitle}
	at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1059)
	at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:997)
	at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1181)
	at java.base/java.lang.String.replaceAll(String.java:2142)
	at com.epam.reportportal.jbehave.ReportPortalStoryReporter.formatExampleStep(ReportPortalStoryReporter.java:314)
	at com.epam.reportportal.jbehave.ReportPortalStoryReporter.buildStartStepRq(ReportPortalStoryReporter.java:344)
	at com.epam.reportportal.jbehave.ReportPortalScenarioStoryReporter.buildStartStepRq(ReportPortalScenarioStoryReporter.java:77)
	at com.epam.reportportal.jbehave.ReportPortalStoryReporter.startStep(ReportPortalStoryReporter.java:564)
	at com.epam.reportportal.jbehave.ReportPortalStoryReporter.lambda$beforeStep$33(ReportPortalStoryReporter.java:836)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.epam.reportportal.jbehave.ReportPortalStoryReporter.beforeStep(ReportPortalStoryReporter.java:836)
	at org.vividus.reportportal.jbehave.AdaptedReportPortalStoryReporter.beforeStep(AdaptedReportPortalStoryReporter.java:65)
	at org.jbehave.core.reporters.DelegatingStoryReporter.lambda$beforeStep$18(DelegatingStoryReporter.java:179)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.jbehave.core.reporters.DelegatingStoryReporter.delegate(DelegatingStoryReporter.java:243)
```

**Comment by HardNorth** [comment]
Fixed: https://github.com/reportportal/agent-java-jbehave/releases/tag/5.1.1
